user:
    public_key: "0409eb9224f408ece7163f40a33274d99b6b3f60e41b447dd45fcc6371f57b88d9d3583c358b1ea8aea4422d17c57de1418554d3a1cd620ca4cb296357888ea596"
    encrypted_private_key:
    ip: "127.0.0.1"
    block_path:
network:
    name: "CrankyCoin"
    version: "0.1"
    initial_coins_per_block: 50
    halving_frequency: 210000
    max_transactions_per_block: 2000
    minimum_hash_difficulty: 4
    target_time_per_block: 600
    difficulty_adjustment_span: 100
    significant_digits: 8
    full_node_port: 30013
    nodes_url: "http://{}:{}/nodes"
    transactions_url: "http://{}:{}/transactions"
    block_url: "http://{}:{}/block/{}"
    blocks_range_url: "http://{}:{}/blocks/{}/{}"
    blocks_url: "http://{}:{}/blocks"
    transaction_history_url: "http://{}:{}/address/{}/transactions"
    balance_url: "http://{}:{}/address/{}/balance"
    default_nodes:
        - "127.0.0.1"
        - "127.0.0.2"
